# Generated by Django 6.0.4 on 2026-04-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0003_processingsettings_llm_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processrun",
            name="extracted_text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
