# Generated by Django 6.0.4 on 2026-04-28 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0008_add_anthropic_provider_choice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="processingsettings",
            options={
                "verbose_name": "Processing Settings",
                "verbose_name_plural": "Processing Settings",
            },
        ),
    ]
