# Generated by Codex on 2026-04-28

from django.db import migrations


def normalize_ocr_provider_values(apps, schema_editor):
    ProcessingSettings = apps.get_model("processing", "ProcessingSettings")
    SourceImage = apps.get_model("processing", "SourceImage")

    ProcessingSettings.objects.filter(ocr_provider="ollama_vision").update(
        ocr_provider="ollama"
    )
    SourceImage.objects.filter(ocr_provider="ollama_vision").update(
        ocr_provider="ollama"
    )


def revert_ocr_provider_values(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0009_alter_processingsettings_options"),
    ]

    operations = [
        migrations.RunPython(
            normalize_ocr_provider_values,
            revert_ocr_provider_values,
        ),
    ]
