# Generated by Django 6.0.4 on 2026-04-29 04:41

import apps.processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0011_alter_extracteddeposit_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingsettings",
            name="valid_consignation_month",
            field=models.PositiveSmallIntegerField(
                default=apps.processing.models.default_valid_consignation_month
            ),
        ),
        migrations.AddField(
            model_name="processingsettings",
            name="valid_consignation_year",
            field=models.PositiveSmallIntegerField(
                default=apps.processing.models.default_valid_consignation_year
            ),
        ),
    ]
